import { describe, expect, it, vi } from 'vitest';
import { handleConsultationIntake } from '../src/pages/api/consultation-intake';
const config:any={enabled:true,fallbackUrl:'https://fallback.test',allowedOrigins:['https://aoifuture.com'],allowedHostnames:['aoifuture.com'],turnstileSiteKey:'',turnstileSecretKey:'',requireTurnstile:false,notionApiKey:'k',notionDataSourceId:'ds',notionApiVersion:'2025-09-03'};
const body=()=>({schemaVersion:'2026-07-14',idempotencyKey:'123e4567-e89b-42d3-a456-426614174000',stage:'workflow_review',situation:'A real workflow problem',email:'test@example.com',consent:{privacyPolicy:true,noSensitiveData:true,version:'2026-07-14'},antiSpam:{turnstileToken:'',website:'',formStartedAt:Date.parse('2026-07-14T11:59:50Z')},source:'direct'});
const req=(payload:any=body(),headers:Record<string,string>={})=>new Request('https://aoifuture.com/api/consultation-intake',{method:'POST',headers:{origin:'https://aoifuture.com','content-type':'application/json',...headers},body:JSON.stringify(payload)});
const now=()=>new Date('2026-07-14T12:00:00Z');
describe('consultation API',()=>{
 it('rejects disabled, origin, media type and schema',async()=>{expect((await handleConsultationIntake(req(),{config:{...config,enabled:false}})).status).toBe(503);expect((await handleConsultationIntake(new Request('https://x.test',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'}),{config})).status).toBe(403);expect((await handleConsultationIntake(req(body(),{'content-type':'text/plain'}),{config})).status).toBe(415);expect((await handleConsultationIntake(req({...body(),extra:true}),{config,now})).status).toBe(400);});
 it('returns created only after store create',async()=>{const store:any={findByIdempotencyKey:vi.fn(async()=>null),enforceRateLimits:vi.fn(async()=>({allowed:true})),create:vi.fn(async()=>({receiptId:'AOI-TEST0001',pageId:'p'}))};const res=await handleConsultationIntake(req(),{config,store,now,receipt:()=> 'AOI-TEST0001'});expect(res.status).toBe(201);expect(await res.json()).toEqual({ok:true,receiptId:'AOI-TEST0001',duplicate:false});expect(store.create).toHaveBeenCalledOnce();});
 it('returns durable duplicate and skips rate/create',async()=>{const store:any={findByIdempotencyKey:vi.fn(async()=>({receiptId:'AOI-OLD',pageId:'p'})),enforceRateLimits:vi.fn(),create:vi.fn()};const res=await handleConsultationIntake(req(),{config,store,now});expect(res.status).toBe(200);expect(await res.json()).toMatchObject({duplicate:true,receiptId:'AOI-OLD'});expect(store.create).not.toHaveBeenCalled();});
 it('returns 429 and 503 without a success receipt',async()=>{const limited:any={findByIdempotencyKey:async()=>null,enforceRateLimits:async()=>({allowed:false,reason:'global_hourly_limit'})};expect((await handleConsultationIntake(req(),{config,store:limited,now})).status).toBe(429);const down:any={findByIdempotencyKey:vi.fn(async()=>null),enforceRateLimits:async()=>({allowed:true}),create:async()=>{throw new Error('down')}};const res=await handleConsultationIntake(req(),{config,store:down,now});expect(res.status).toBe(503);expect(await res.text()).not.toContain('receiptId');});
 it('fails closed when Turnstile is required but absent',async()=>expect((await handleConsultationIntake(req(),{config:{...config,requireTurnstile:true},now})).status).toBe(503));
});
